POST http://localhost:3000/login
Content-Type: application/json
{
  "username": "christopher_phillips",
  "password": "christy@123"
}

GET http://localhost:3000/states
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA5OTY5NzU0fQ.rc_Zlp7eERV4xPcYKAyA3-WySuL3PS-7Bpw5ePxdVQQ

GET http://localhost:3000/states/8/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA5OTY5NzU0fQ.rc_Zlp7eERV4xPcYKAyA3-WySuL3PS-7Bpw5ePxdVQQ

POST http://localhost:3000/districts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA5OTY5NzU0fQ.rc_Zlp7eERV4xPcYKAyA3-WySuL3PS-7Bpw5ePxdVQQ
Content-Type: application/json
{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

GET http://localhost:3000/districts/325
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA5OTY5NzU0fQ.rc_Zlp7eERV4xPcYKAyA3-WySuL3PS-7Bpw5ePxdVQQ

DELETE http://localhost:3000/districts/321
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA5OTY5NzU0fQ.rc_Zlp7eERV4xPcYKAyA3-WySuL3PS-7Bpw5ePxdVQQ

PUT http://localhost:3000/districts/325
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA5OTY5NzU0fQ.rc_Zlp7eERV4xPcYKAyA3-WySuL3PS-7Bpw5ePxdVQQ
Content-Type: application/json
{
  "districtName": "adia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}